---
- hosts: pihole
  roles:
    - {role: install-docker, tags: ['install-docker']}
    - {role: disable-dns-stub-resolver, tags: ['disable-dns-stub-resolver']}
    - {role: docker-compose-template, tags: ['docker-compose-template']}
