---
site_name: infra
site_description: Infrastructure as code
site_url: https://infra.iancleary.me

theme:
    name: 'material'

repo_name: iancleary/infra
repo_url: https://github.com/iancleary/infra
edit_uri: 'blob/main'

nav:
    - Introduction: 'index.md'
    - Start with the Makefile: 'makefile.md'
