---
site_name: ansible-desktop
site_description: Ansible Configuration of Ubuntu LTS Desktops!
site_url: https://ansible-desktop.iancleary.me

theme:
    name: 'material'

repo_name: iancleary/ansible-desktop
repo_url: https://github.com/iancleary/ansible-desktop
edit_uri: 'blob/main'

nav:
    - Introduction: 'index.md'
    - Start with the Makefile: 'makefile.md'
