---
- name: Disable DNSStubResolver in system-resolved.conf
  become: true
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener=yes'
    line: DNSStubListener=no
  register: resolved

- name: Force update /etc/resolv.conf symlink
  become: true
  file:
    src: "/etc/resolv.conf"
    dest: "/run/systemd/resolve/resolv.conf"
    state: link
    force: yes
  register: symlink

- name: Disable clout-init's network configuration capabilities
  become: true
  template:
    src: 99-disable-network-config.cfg.j2
    dest: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg'
    mode: 'u=rw,go=r'

- name: Edit netplan
  become: true
  template:
    src: 50-cloud-init.yaml.j2
    dest: '/etc/netplan/50-cloud-init.yaml'
    mode: 'u=rw,go=r'

- name: Reload or restart systemd-resolved
  become: true
  command: systemctl reload-or-restart systemd-resolved
  when: symlink.changed or resolved.changed

- name: Reload or restart dnsmasq
  become: true
  command: systemctl reload-or-restart dnsmasq
  when: symlink.changed or resolved.changed
