---
dns:
  hosts:
    pihole:
      ansible_host: 192.168.1.66
      ansible_user: "administrator"

development:
  hosts:
    code_server:
      ansible_host: 192.168.1.65
      ansible_user: "administrator"
    docker_test:
      ansible_host: 192.168.1.67
      ansible_user: "administrator"