---
- name: install apt package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker's official GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# 20.04 has everything needed within Ubuntu's repositories
- name: Setup Stable Repository 18.04
  become: true
  apt_repository:
    repo: >-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  when: ansible_distribution_version == "18.04"

- name: install 18.04
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: "yes"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_distribution_version == "18.04"

- name: install 20.04
  become: true
  apt:
    name: docker.io
    state: latest
    update_cache: "yes"
  when: ansible_distribution_version == "20.04"

- name: Create the docker group
  group:
    name: docker
    state: present

- name: Add your user to the group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: ["docker"]
    append: "yes"

- name: Start Docker on boot
  become: true
  service:
    name: "docker"
    enabled: "yes"

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

# - name: Delete existing docker-compose version if it's different.
#   become: true
#   file:
#     path: "{{ docker_compose_path }}"
#     state: absent
#   when: >
#     docker_compose_current_version.stdout is defined
#     and docker_compose_version not in docker_compose_current_version.stdout
# - name: Install Docker Compose (if configured).
#   become: true
#   get_url:
#     url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ docker_compose_arch }}
#     dest: "{{ docker_compose_path }}"
#     mode: 0755

# Docker Compose on armv7l GitHub Issue -> APT install for now
# https://github.com/docker/compose/issues/6831#issuecomment-568815378

- name: Install Docker Compose
  become: true
  apt:
    name: "docker-compose"
    state: latest
